### ISSUE TITLE
请教一个问题：我把pom里的springboot换成2.2.x或者2.3.x就不行了

### ISSUE THREAD

**Issue by cctvkill1** [JiekerTime/QuickStartOfShardingSphereJDBC#9]
你好，请教一个问题：我把pom里的springboot换成2.2.x或者2.3.x就启动不了
然后也升级了 mysql、mybatis的版本 ，使用druid  启动不了
        <shardingsphere.version>5.0.0-alpha</shardingsphere.version>
        <spring-boot.version>2.3.0.RELEASE</spring-boot.version>
        <druid.version>1.1.22</druid.version>
        <mysql-connector-java.version>8.0.21</mysql-connector-java.version>
        <mybatis-spring.version>2.1.3</mybatis-spring.version>
注释掉config下的包
启动可以了 但是报错 The database URL cannot be null.
然后解开config里的注释 启动报错  at org.apache.shardingsphere.spring.boot.datasource.DataSourceMapSetter.getDataSourceMap
应该是spring.shardingsphere.datasource.common的问题
这种情况应该怎么解决呢？

**Comment by JiekerTime** [comment]
谢谢你的issue 其实我某处注解中有写 SS alpha在2.X以后就必须从数据源中抽取一层common数据源 不然会报错 
这个问题在beta得以解决 
希望你能够帮助到你

**Comment by cctvkill1** [comment]
非常感谢你的回复。
确实 你的代码里DataSourceUtil中有TODO configure the common datasource
最近正在使用shardingSphere做数据库中间件，着实踩了不少坑。
beta版暂时还不知道什么时候发布，看来只有等待了

**Comment by JiekerTime** [comment]
嗯呢 ShardingSphere正在发展中 但是大体都是比较稳定的 ~

**Comment by JiekerTime** [comment]
嗯呢 ShardingSphere虽然正在发展中 但是基本上还是比较稳定的 如果遇到了什么问题 可以随时和我联系一起讨论~
SS 的beta版或将在不远的未来带着更多更丰富的功能发布 尽请期待~ 
那我这个issue暂时关闭了哦！
